
export const countryAddress = [
	
            'Andhra Pradesh - Adilabad',
			'Andhra Pradesh - Anantapur',
			'Andhra Pradesh - Chittoor',
			'Andhra Pradesh - Kakinada',
			'Andhra Pradesh - Guntur',
			'Andhra Pradesh - Hyderabad',
			'Andhra Pradesh - Karimnagar',
			'Andhra Pradesh - Khammam',
			'Andhra Pradesh - Krishna',
			'Andhra Pradesh - Kurnool',
			'Andhra Pradesh - Mahbubnagar',
			'Andhra Pradesh - Medak',
			'Andhra Pradesh - Nalgonda',
			'Andhra Pradesh - Nizamabad',
			'Andhra Pradesh - Ongole',
			'Andhra Pradesh - Hyderabad',
			'Andhra Pradesh - Srikakulam',
			'Andhra Pradesh - Nellore',
			'Andhra Pradesh - Visakhapatnam',
			'Andhra Pradesh - Vizianagaram',
			'Andhra Pradesh - Warangal',
			'Andhra Pradesh - Eluru',
			'Andhra Pradesh - Kadapa',
			'Delhi - Central Delhi',
			'Delhi - East Delhi',
			'Delhi - New Delhi',
			'Delhi - North Delhi',
			'Delhi - North East Delhi',
			'Delhi - North West Delhi',
			'Delhi - South Delhi',
			'Delhi - South West Delhi',
			'Delhi - West Delhi',
			'Goa - North Goa',
			'Goa - South Goa',
			'Gujarat - Ahmedabad',
			'Gujarat - Amreli district',
			'Gujarat - Anand',
			'Gujarat - Banaskantha',
			'Gujarat - Bharuch',
			'Gujarat - Bhavnagar',
			'Gujarat - Dahod',
			'Gujarat - The Dangs',
			'Gujarat - Gandhinagar',
			'Gujarat - Jamnagar',
			'Gujarat - Junagadh',
			'Gujarat - Kutch',
			'Gujarat - Kheda',
			'Gujarat - Mehsana',
			'Gujarat - Narmada',
			'Gujarat - Navsari',
			'Maharashtra - Ahmednagar',
			'Maharashtra - Akola',
			'Maharashtra - Amravati',
			'Maharashtra - Aurangabad',
			'Maharashtra - Bhandara',
			'Maharashtra - Beed',
			'Maharashtra - Buldhana',
			'Maharashtra - Chandrapur',
			'Maharashtra - Dhule',
			'Maharashtra - Gadchiroli',
			'Maharashtra - Gondia',
			'Maharashtra - Hingoli',
			'Maharashtra - Jalgaon',
			'Maharashtra - Jalna',
			'Maharashtra - Kolhapur',
			'Maharashtra - Latur',
			'Maharashtra - Mumbai City',
			'Maharashtra - Mumbai suburban',
			'Maharashtra - Nandurbar',
			'Maharashtra - Nanded',
			'Maharashtra - Nagpur',
			'Maharashtra - Nashik',
			'Maharashtra - Osmanabad',
			'Maharashtra - Parbhani',
			'Maharashtra - Pune',
			'Rajasthan - Ajmer',
			'Rajasthan - Alwar',
			'Rajasthan - Bikaner',
			'Rajasthan - Barmer',
			'Rajasthan - Banswara',
			'Rajasthan - Bharatpur',
			'Rajasthan - Baran',
			'Rajasthan - Bundi',
			'Rajasthan - Bhilwara',
			'Rajasthan - Churu',
			'Rajasthan - Chittorgarh',
			'Rajasthan - Dausa',
			'Rajasthan - Dholpur',
			'Rajasthan - Dungapur',
			'Rajasthan - Ganganagar',
			'Rajasthan - Hanumangarh',
			'Rajasthan - Jhunjhunu',
			'Rajasthan - Jalore',
			'Rajasthan - Jodhpur',
			'Rajasthan - Jaipur',
			'Rajasthan - Jaisalmer',
			'Rajasthan - Jhalawar',
			'Rajasthan - Karauli',
			'Rajasthan - Kota',
			'Rajasthan - Nagaur',
			'Rajasthan - Pali',
			'Rajasthan - Pratapgarh',
			'Rajasthan - Rajsamand',
			'Rajasthan - Sikar'
]




